language: node_js
node_js:
- 7.8

before_script:
- pip install mbutil --user

script:
- npm run build

after_success: bash ./bin/deploy.sh

env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: miya0001@users.noreply.github.com
  - GH_REF: github.com/ogijima-library/map
  - secure: "aRRXV5Go6F/iZH24IScnarM1Ur9WxsoveWcAbgXhISwD53IcnlSWA52rbWbsUDTKbziFOJwAlW19tTz33GCw1SQz4ZI/CTiaR37ZtX3XF2efA+KiVIaddyLmoebDDkKQ9CPEIhvAeOrTeAdtksGPm5csh4q3gHXEmFjly5JxNtGKFZ9QQWLKHwVYkOW577T+iXqRR8pZSsmf99KcEvrdzdqR7j5J1oMrm6rlC88PkOkIXkKLLIExl0m4/eLE602nAwNTx41CcZAsCGcQ4uGlrrEJhNl4AFuH3KR9qwDNADwIjBWlHcgsIFjXZtmSYyh4fxeE9MP5qJcLkinRCBDCLDV1m0Oe34O2IEAKWo1qYaZEEnWTIo+Ofr+Z8CLvUBR0qr3R3ykHWruUCrg4kA85siYokhg542ndU4SMuK4Zui9tp2M69M9hADEuZNw5fQySEpmY9XmP1MsMxsJqXwTmouw9gbRiGSLdm5YNF77iSDmch6SQlgXfqLE+gOIowRyEX5AJ92BQOAvcr8xjrJl0BLRP2aXEV24Br5gxlxx3SP6PhQ2HGOTLL3o11u4K/eges5cRASshq64rbD0rJho8LrxliQQdMkxH+n4Lf4fQwV+C/7h0m8FJGaOPATrweerYZTh3d/zGQ3ypTiNWXb/nDnr0meziHP8M5nvakm6uMsQ="
